language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
services:
  - riak
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq valgrind
before_script:
  - git submodule update --init --recursive
  - ./script/build_module.sh
script:
  - sudo search-cmd install testsearch
  - PHP=`which php`
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -q -m --show-diff
  - find . -name *.mem | xargs cat
